### ISSUE TITLE
血量冲突问题解决❤

### ISSUE THREAD

**Issue by Caishangqi** [Caishangqi/GonerAge#22]
# 血量问题概述 ❤
## 概述
由于Deathpunishment的血量减少惩罚在执行时会扣除玩家血量, scalinghealth会重置扣除后玩家血量,直至1点(半个❤)并且会记录负数值直至最小数字

## 解决方案
以及调整Deathpunishment的扣除机制并且取消了负数血量上限,但是之受到影响的玩家需要重置其账号来清除人物属性。解决方法在此问题下留下其对应家的位置坐标并且将身上物品储存箱子中等待我们帮你刷新人物

## 修复后指令结果
`org.bukkit.command.CommandException: Unhandled exception executing command 'deathpunishment' in plugin deathPunishment v1.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServerAsync-1.12.2-08cb86c]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServerAsync-1.12.2-08cb86c]
at org.bukkit.craftbukkit.v1_12_R1.Cra[控制面板]: 无法读取更多的服务端日志: 已到最顶端.. [_b_r_]ftServer.dispatchCommand(CraftServer.java:709) ~[CraftServer.class:git-CatServerAsync-1.12.2-08cb86c]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_251]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_251]
at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:473) [nz.class:?]`

## 结果
已经测试3个小号及其死亡后效果,已经成功解决此问题,但是最高血量上限增加需要设置模组配置参数来取消上限突破后扣血问题,下次配置更新时修复~

**Comment by 1504879303** [comment]
![qqq](https://user-images.githubusercontent.com/66978429/85080344-84bb5a80-b1fb-11ea-9371-c42a4a4a473e.png)
导致一直扣血 回血 传送一直没法完成，运气好 1 2次 运气不好昨天back了12次
